app/Models/Holiday.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use App\Repositories\Eloquent\HasCompanyScopes;
use Illuminate\Support\Facades\Auth;

class Holiday extends Model
{
    use HasCompanyScopes;

    protected $fillable = ['from','to','name','is_annual','company_id'];

    public $dates = ['from','to'];

    public function getRangeAttribute(){
        $date = Carbon::parse($this->from)->setTimezone(Auth::user()->companyTimezone)->format('m/d/Y') . ' - ' . $this->to->format('m/d/Y');
        return $date;
    }

}

app/Http/Controllers/Admin/SettingsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Client;
use App\Models\Color;
use App\Models\Format;
use App\Models\Holiday;
use App\Models\Key;
use App\Models\Report;
use App\Models\Stage;
use App\Models\Role;
use App\Models\Department;
use App\Models\Subscription;
use App\Models\User;
use App\Services\Avengate\src\SoapClient;
use App\Services\Uploaders\Uploader;
use Carbon\Carbon;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Option;
use Illuminate\Filesystem\Filesystem;

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;

use App\Services\ColorServer;
use App\Services\TimezoneService;

use Illuminate\Support\Facades\Auth;

use Barryvdh\Snappy\Facades\SnappyPdf as PDF;

class SettingsController extends Controller
{

    use ColorServer;
    use TimezoneService;

    public $pageTitle = "Settings";

	public function __construct(Option $option, Filesystem $filesystem){
		$this->option = $option;
		$this->filesystem = $filesystem;
        $this->userIconDirectory = 'public/images/icons/user-icons';

	}

    public function index(){

        if(!Auth::user()->isAdmin)
            return redirect(route('calendar.year'));

        $userIcons = $this->getFileNames($this->filesystem->files($this->userIconDirectory));

        $options = $this->option->fromCurrentCompany()->lists('value','name');

        $options['workdays'] = isset($options['workdays']) ? json_decode($options['workdays']) : null;

        $roles = Role::get();
        $formats = Format::fromCurrentCompany()->orderBy('name','ASC')->get();
        $roleList = Role::orderBy('name','ASC')->lists('name','id');
        $departments = Department::fromCurrentCompany()->with('users')->orderBy('name','ASC')->get();

        $departmentList = Department::fromCurrentCompany()->orderBy('name','ASC')->lists('name','id');
        $stages = Stage::with('department')->fromCurrentCompany()->orderBy('order','ASC')->get();
        $colors = $this->getColors();
        $timezones = $this->getTimezones();
        $clients = Client::fromCurrentCompany()->orderBy('name','ASC')->get();
        $keys = Key::fromCurrentCompany()->orderBy('name','ASC')->get();

        $company = Auth::user()->company;

        $this->reduceUsers($company->activeUsers,$company->subscription->plan->max_users);

        $unassigned_users = User::whereDoesntHave('department')->where('company_id',Auth::user()->company->id)->get();

        $admins = User::whereHas('role', function($query){
            $query->where('role_id',1);
        })->get();

        $holidays = Holiday::where('company_id',$this->currentCompanyId())->orderBy('from')->get();

        $reports = Report::fromCurrentCompany()->where('type','email-reports')->first();

        $subscription = $company->subscription;

        return view('pages.settings.index',compact('subscription','reports','unassigned_users','holidays','options','userIcons','roles','roleList','departments','departmentList','stages','formats','timezones','colors','clients','keys'));
    }

    public function samplePDF(){

        $userIcons = $this->getFileNames($this->filesystem->files($this->userIconDirectory));

        $options = $this->option->fromCurrentCompany()->lists('value','name');

        $options['workdays'] = isset($options['workdays']) ? json_decode($options['workdays']) : null;

        $roles = Role::get();
        $formats = Format::fromCurrentCompany()->get();
        $roleList = Role::lists('name','id');
        $departments = Department::fromCurrentCompany()->with('users')->get();
        $departmentList = Department::fromCurrentCompany()->lists('name','id');
        $stages = Stage::with('department')->fromCurrentCompany()->orderBy('order','ASC')->get();
        $colors = $this->getColors();
        $timezones = $this->getTimezones();
        $clients = Client::fromCurrentCompany()->get();

        $pdf = App::make('snappy.pdf.wrapper');
        $pdf->loadView('pages.settings.index', compact('options','userIcons','roles','roleList','departments','departmentList','stages','formats','timezones','colors','clients'));
        return $pdf->inline();
    }

    public function store(Request $request){

        $input = $request->except('_token','logo','workdays','crop');
        $logo = $request->file('logo');
        $company_id = $this->currentCompanyId();

        if(isset($input['company_id']))
            $company_id = $input['company_id'];

        foreach ($input as $key => $value) {
        	$option = $this->option->fromCompany($company_id)->where('name',$key)->first();

        	if($option)
        		$option->update(array('value'=>$value));
        	else
        		$option = $this->option->create(array('name'=>$key,'value'=>$value,'company_id'=>$company_id));
        }

        $workDays = $request->input('workdays');

        if(count($workDays)){
            $option = $this->option->where('name','workdays')->fromCompany($company_id)->first();

            if($option)
                $option->update(array('value'=>json_encode($workDays)));
            else
                $this->option->create(array('name'=>'workdays','value'=>json_encode($workDays),'company_id'=>$company_id));
        }


        if($logo)
            $this->uploadLogo($logo,$company_id,$request);

        Session::flash('message','Company details updated.');
        return redirect()->back();
    }

    private function getFileNames($files){
        $data = [];

        foreach($files as $key=>$file){
            $fileName = str_replace($this->userIconDirectory.'/',"",$file);
            $data[$fileName] = preg_replace('/\\.[^.\\s]{3,4}$/', '', $fileName);
        }

        return $data;
    }

    private function uploadLogo($logo,$company_id = null,$request = null){

        if(!$company_id)
            $company_id = $this->currentCompanyId();

        $imageName = Str::random('36') . '.' . $logo->getClientOriginalExtension();

        $logo = Image::make($logo->getRealPath());
        $path = public_path('uploads/logo/' . $imageName);

        $crop = $request->input('crop');

        $uploadedLogo = $logo->resize($crop['max_width'],$crop['max_height'])->crop(intval($crop['w']), intval($crop['h']), intval($crop['x']), intval($crop['y']))->save($path);

        if($uploadedLogo){
            $existingLogo = Option::where('name','logo')->where('company_id',$company_id)->first();
            
            if($existingLogo)
                $existingLogo->update(array('value'=>$imageName));
            else
                $this->option->create(array('name'=>'logo','value'=>$imageName,'company_id'=>$company_id));
        }
    }


    public function reduceUsers($activeUsers,$max_users){
        $employees = 0;

        foreach($activeUsers as $employee){
            if(!$employee->department && $employee->isEmployee){
                $employee->is_active = 0;
                $employee->save();
            }
        }

        if($max_users < count($activeUsers)){
            foreach($activeUsers as $employee){

                if($employees < $max_users){
                    $employees++;
                }
                else {
                    $employee->is_active = 0;
                    $employee->save();
                }
            }
        }

    }

    public function storeReports(Request $request){

        $input = $request->input();

        $company = Auth::user()->company;
        $now = Carbon::now()->setTimezone(Auth::user()->company->timezone)->format('Y-m-d');

        $report = Report::where('type','email-reports')->where('company_id',$company->id)->first();
        $time = Carbon::parse($now.' '.$input['time'] ,$company->timezone);
        $time = $time->setTimezone('UTC');
        $day = null;
        $month = null;
        $week_day = null;

        if($input['interval']=='w'){
            for($x=0;$x<7;$x++){
                if(Carbon::now()->addDays($x)->setTimezone(Auth::user()->company->timezone)->format('D')==$input['week-day']){
                    $now = Carbon::now()->addDays($x)->setTimezone(Auth::user()->company->timezone)->format('Y-m-d');
                    $week_day = $input['week-day'];
                    break;
                }
            }
        }

        elseif($input['interval']=='m'){
            for($x=0;$x<32;$x++){
                if(intval(Carbon::now()->addDays($x)->setTimezone(Auth::user()->company->timezone)->format('d'))==intval($input['month-day'])){
                    $now = Carbon::parse(Carbon::now()->format('Y').'-'.Carbon::now()->addDays($x)->setTimezone(Auth::user()->company->timezone)->format('m-d'))->format('Y-m-d');
                    $day = Carbon::parse(Carbon::now()->format('Y').'-'.Carbon::now()->addDays($x)->setTimezone(Auth::user()->company->timezone)->format('m-d'))->format('d');
                    break;
                }
            }
        }

        elseif($input['interval']=='y'){

            $next = Carbon::parse(Carbon::now()->format('Y').'-'.$input['month'].'-'.$input['day']);

            if($next->diffInDays(Carbon::now(),false) > 0)
                $next->addYear();

            $now = $next->format('Y-m-d');
            $day = $input['day'];
            $month = $input['month'];
        } else {
            $now = Carbon::now()->setTimezone(Auth::user()->company->timezone)->addDay()->format('Y-m-d');
        }

        $next_send = Carbon::parse($now.' '.$time->format('H:i') ,$company->timezone);

        if(!$report)
            $company->reports()->create([
                'interval' => $input['interval'],
                'time' => $time->format('H:i'),
                'type' => 'email-reports',
                'day' => $day,
                'week_day' => $week_day,
                'month' => $month,
                'next_send' => $next_send,
            ]);
        else
            $report->update([

resources/views/pages/settings/_clients-edit.blade.php
<div id="editClientModal" class="modal fade" data-backdrop="static" data-keyboard="false" role="dialog">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center" style="width: 300px">

            <!-- Modal content-->
            <div class="modal-content clearfix">
                {!! Form::open(['id'=>'clientEditForm','route'=>'api.clients.update','class'=>'pull-left width-full']) !!}

                @if(isset($company))
                    <input type="hidden" name="company_id" value="{{ $company->id }}">
                @endif

                <div class="modal-header clearfix">
                    <h4 class="modal-title">Edit Client</h4>
                </div>
                <div class="modal-body clearfix width-full">

                    <input type="hidden" name="id" value="0">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="color-label">
                                <p class="pull-left">Name</p>
                                <p class="pull-right"><input id="clientEditColor" class="form-control" name='color' value='#3355cc'/></p>
                            </div>
                            <div class="form-group relative pull-left width-full">
                                <input type="text" class="form-control margin-b-5" name="name" placeholder="Name" value="" required="required" maxlength="30">
                            </div>
                        </div>
                    </div>

                </div>

                    <div class="modal-footer clearfix pull-left width-full">
                        {!! Form::submit('Save',['class'=>'createbt btn btn-default margin-b-0']) !!}
                        <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                    </div>
                {!! Form::close() !!}
            </div>

        </div>
    </div>
</div>

resources/views/pages/settings/_employees-edit-modal.blade.php
<div id="editUserModal" class="modal fade" data-backdrop="static" data-keyboard="false" role="dialog">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center" style="width: 300px">
            <!-- Modal content-->
            <div class="modal-content clearfix">
            {!! Form::open(['id'=>'userEditForm','route'=>'api.users.update','class'=>'']) !!}
              <div class="modal-header clearfix">
                <h4 class="modal-title">Edit User</h4>
              </div>
              <div class="modal-body clearfix width-full">
                <div class="row">
                    <div class="col-md-12">
                        <input type="hidden" name="id" value="0">
                        Name:
                        <input type="text" class="form-control" name="name" placeholder="Full Name" maxlength="30" value="" required="required">
                        Department:
                        <div class="small margin-b-7">
                            {!! Form::select('department_id',$departmentList, null ,['id'=>'department_select','class'=>'selectpicker department_select']) !!}
                        </div>

                        Role:
                        <div class="small margin-b-7">
                            {!! Form::select('role_id',$roleList, null ,['id'=>'edit_user_role_select','class'=>'selectpicker']) !!}
                        </div>
                        <div id="scheduler-for">
                            Scheduler for:
                            <div class="small margin-b-7">
                                {!! Form::select('scheduler_department_id',$departmentList, null ,['id'=>'edit_user_scheduler_department','class'=>'selectpicker']) !!}
                            </div>
                        </div>
                        Email:
                        <input type="text" class="form-control" name="email" maxlength="30" placeholder="Email Address" value="" required="required">


                    </div>
                </div>

              </div>
              <div class="modal-footer clearfix pull-left width-full">
                    {!! Form::submit('Save',['id'=>'sendInvite','class'=>'btn btn-default margin-tb-0']) !!}
                    <button class="btn btn-default" data-dismiss="modal">Cancel</button>
              </div>
            {!! Form::close() !!}
            </div>
          </div>
    </div>

</div>

resources/views/pages/settings/_formats-edit.blade.php
<div id="editFormatModal" class="modal fade" data-backdrop="static" data-keyboard="false" role="dialog">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center" style="width: 300px">

            <!-- Modal content-->
            <div class="modal-content clearfix">
                {!! Form::open(['id'=>'formatEditForm','route'=>'api.formats.update','class'=>'pull-left width-full']) !!}
                @if(isset($company))
                    <input type="hidden" name="company_id" value="{{ $company->id }}">
                @endif

                <div class="modal-header clearfix">
                    <h4 class="modal-title">Edit Deliverable</h4>
                </div>
                <div class="modal-body clearfix width-full">

                    <input type="hidden" name="id" value="0">
                    <div class="col-md-12">
                        <div class="row">
                            <input type="text" class="form-control margin-b-5" name="name" placeholder="Name" value="" required="required" maxlength="30">
                        </div>
                    </div>
                </div>

                <div class="modal-footer clearfix pull-left width-full">
                    {!! Form::submit('Save',['class'=>'createbt btn btn-default margin-b-0']) !!}
                    <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>

                {!! Form::close() !!}
            </div>

        </div>
    </div>
</div>

resources/views/pages/settings/_holidays-delete.blade.php
<!-- Modal -->
<div id="deleteHolidayModal" class="modal fade delete" data-backdrop="static" data-keyboard="false" role="dialog">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center" style="width: 250px">

            <!-- Modal content-->
            <div class="modal-content text-center">
                <div class="modal-header">
                    <h4 class="modal-title">Delete Holiday</h4>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this? Please type "yes" to confirm.<br>
                    {!! Form::open(['route'=>'api.formats.delete']) !!}
                        <input type="hidden" id="deleteHoliday" name="id">
                        <input id="deleteHolidayConfirmInput" class="text-center">
                    {!! Form::close() !!}
                </div>
                <div class="modal-footer text-center-important">
                    <button id="deleteHolidayTrigger" class="createbt btn btn-default confirmBt">Confirm</button>
                    <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>

            </div>

        </div>
    </div>
</div>

resources/views/pages/settings/_holidays.blade.php
@section('holidays-style')
@endsection

<hr>
<div class="row">
    <div class="row">
        <div class="col-md-8">
            {!! Form::open(['id'=>'holidaysForm','route'=>'api.holidays.store']) !!}

            @if(isset($company))
                <input type="hidden" name="company_id" value="{{ $company->id }}">
            @endif

            <div class="col-md-4">
                Holidays
                <div class="form-group relative">
                    <input type="text" class="form-control margin-b-5" name="name" placeholder="Add Holiday Name" value="" maxlength="30">
                </div>
            </div>
            <div class="col-md-4 padding-l-0 ">
                Dates
                <div class="form-group relative width-full">
                    <input type="text" class="form-control margin-b-5" id="holidate" name="date" placeholder="D-M-Y to D-M-Y" value="" maxlength="30">
                </div>
            </div>
            <div class="col-md-2 padding-r-0 padding-l-0">
                Annual
                <div class="small">
                    <select name="is_annual" class=" selectpicker">
                        <option value="1">Yes</option>
                        <option value="0">No</option>
                    </select>
                </div>
            </div>

            <div class="col-md-2 padding-r-0">
                &nbsp;
                <div class="small">
                    {!! Form::submit('Add',['class'=>'link-bt t-pink link-color margin-b-0 divider-left']) !!}
                </div>
            </div>

            <div class="col-md-12 margin-b-10">
                {!! Form::close() !!}
            </div>
        </div>

        <div class="col-md-12">
            <div class="alert row-alert" style="display: none"></div>
            <div class="col-md-12">
                <ul id="holidayList">
                    @if(count($holidays))
                        @foreach($holidays as $holiday)
                            <li>
                                <div class="pull-left t24">
                                    <p class=margin-b-0>{{ $holiday->name }} ({{ $holiday->range }}) {{ $holiday->is_annual ? '(Annual)' : '' }}</p>
                                </div>
                                <div class="margin-l-10 pull-left divider-left">
                                    <a href="#" data-holidayid="{{ $holiday->id }}" class="edit-holiday link-text padding-r-0">Edit</a>
                                </div>
                                <div class="margin-l-10 pull-left divider-left">
                                    <a href="#" data-holidayid="{{ $holiday->id }}" class="delete-holiday delete-icon link-icon"></a>
                                </div>
                            </li>
                        @endforeach
                    @endif
                </ul>
            </div>
        </div>

    </div>
</div>


<!-- Modal -->
@include('pages.settings._holidays-delete')

        <!-- Modal -->
@include('pages.settings._holidays-edit')

@section('holidays-js')
    <script>

        $('#holidate').daterangepicker({
            datepickerOptions : {
                numberOfMonths : 2,
                maxDate: null,
                minDate: null
            },
            presetRanges: [],
            presets: { dateRange: "Date Range" }
        }).on('change', function(e){
            dateRange = (JSON.parse(e.currentTarget.value));
            $(this).closest('div').find('.from').val(moment(dateRange.start).format('MM/DD/Y'));
            $(this).closest('div').find('.to').val(moment(dateRange.end).format('MM/DD/Y'));
        });

        /** SEND CREATE REQUEST **/

        $('#holidaysForm').on('submit', function(e){

            submitBt = $(this).find('input[type=submit]');
            $(submitBt).attr('disabled','disabled');

            var form = $(this);
            processFlag = 1;

            e.preventDefault();
            e.stopPropagation();

            data = form.serialize();
            url = form.attr('action');

            if(processFlag) {
                processFlag = 0;

                $.ajax({
                    type: "POST",
                    url: url,
                    data: data,
                    success: function(response){

                        if(response.status==200) {
                            refreshHolidayList(response.data);
                            $(form).find('input[type=text]').val('');
                        }

                        doAlert(response);

                        $(submitBt).removeAttr('disabled');
                    },
                    done : function (){
                        processFlag = 1;
                    }
                });
            }
        });

        /** SEND DELETE REQUEST **/


        $('#deleteHolidayTrigger').on('click', function(){
            if($('#deleteHolidayConfirmInput').val()=="yes"){
                deleteHoliday();
                $('#deleteHolidayModal').modal('hide');
            } else {
                alert('Please follow the instructions');
            }
        });


        /** SEND UPDATE REQUEST **/

        $('#holidayEditForm').on('submit', function(e){
            var form = $(this);
            processFlag = 1;

            e.preventDefault();
            e.stopPropagation();

            data = form.serialize();
            url = form.attr('action');

            if(processFlag) {
                processFlag = 0;

                $.ajax({
                    type: "POST",
                    url: url,
                    data: data,
                    success: function(response){

                        if(response.status==200) {
                            refreshHolidayList(response.data);
                            $(form).trigger('reset');
                            $(form).closest('.modal').modal('hide');
                        }

                        doAlert(response);
                    },
                    done : function (){
                        processFlag = 1;
                    }
                });
            }
        });


        /*********************************** FUNCTIONS **************************/

        function refreshHolidayList(data){
            $('#holidayList').html('');

            if(data.length) {
                for(var x=0;x<data.length;x++){
                    el =
                            '<li>'+
                                '<div class="pull-left t24">'+
                                    '<p class=margin-b-0>'+data[x]['name']+' ('+moment(data[x]['from']).format('MM/DD/Y')+' - '+moment(data[x]['to']).format('MM/DD/Y')+')'+(data[x]['is_annual'] ? ' (Annual)' : '')+'</p>'+
                                '</div>'+
                                '<div class="margin-l-10 pull-left divider-left">'+
                                    '<a href="#" data-holidayid="'+data[x]['id']+'" class="edit-holiday link-text padding-r-0">Edit</a>'+
                                '</div>'+
                                '<div class="margin-l-10 pull-left divider-left">'+
                                    '<a href="#" data-holidayid="'+data[x]['id']+'" class="delete-holiday delete-icon link-icon"></a>'+
                                '</div>'+
                            '</li>';

                    $('#holidayList').append(el);
                }
                attachDeleteHolidayEvent();
                attachEditHolidayEvent();

                $('#holidayList').closest('.row').find('.alert').hide();
            }
            else {
                $('#holidayList').closest('.row').find('.alert').removeClass('temp-hide').show();
            }
        }


        function deleteHoliday(){

            url = "{{ route('api.holidays.delete') }}";
            data   = $('#deleteHolidayModal form').serialize();
            deleteProcessFlag = 1;

            if(deleteProcessFlag) {
                deleteProcessFlag = 0;

                $.ajax({
                    type: "POST",
                    url: '{{ route('api.holidays.delete') }}',
                    data: data,
                    success: function(response){


                        if(response.status==200){
                            refreshHolidayList(response.data);
                        }

                        doAlert(response);
                    },
                    done : function (){
                        deleteProcessFlag = 1;
                    }
                });
            }
        }

        function attachDeleteHolidayEvent(){
            $('.delete-holiday').on('click', function(e){

                e.preventDefault();

                holidayId = $(this).attr('data-holidayid');

                if(holidayId>0){
                    $('#deleteHolidayModal').modal('show');
                    $('#deleteHoliday').val(holidayId);
                }
            });
        }

        function attachEditHolidayEvent(){
            $('.edit-holiday').on('click', function(e){

                e.preventDefault();

                stageId = $(this).attr('data-holidayid');

                if(stageId>0){

                    $.ajax({
                        type: "GET",
                        url: '{{ route('api.holidays.get') }}?id='+stageId,
                        success: function(response){


                            if(response.status==200){
                                $('#editHolidayModal').modal('show');

                                $.each(response.data, function(i,e){
                                    $('#editHolidayModal input[name='+i+']').val(e);
                                });

                                $('#edit-holidate').daterangepicker({
                                    datepickerOptions : {
                                    numberOfMonths : 2,
                                    maxDate: null,
                                    minDate: null,
                                },
                                presetRanges: [],
                                presets: { dateRange: "Date Range" }
                                });

                                $('#holidayEditForm select[name="is_annual"]').val(response.data.is_annual).trigger('change');

                                setTimeout(function(){
                                    $('#edit-holidate').daterangepicker("setRange", {
                                        start: new Date(response.data.from),
                                        end: new Date(response.data.to)
                                    });

                                },300);

                            } else {
                                doAlert(response);
                            }

                        },
                        done : function (){
                            deleteProcessFlag = 1;
                        }
                    });


                }
            });
        }

        attachDeleteHolidayEvent();
        attachEditHolidayEvent();
    </script>
@endsection

resources/views/pages/settings/_keys-list.blade.php
<div class="col-md-12">
    <div class="alert row-alert" style="display: none"></div>
    <div class="col-md-12">
        <ul id="keyList">
            @if(count($keys))
                @foreach($keys as $key)
                    <li>
                        <div class="pull-left t24">
                            <p class=margin-b-0>{{ $key->name }} ({{ $key->department->name }})</p>
                        </div>
                        <div class="margin-l-10 pull-left divider-left">
                            <a href="#" data-keyid="{{ $key->id }}" class="edit-key link-text padding-r-0">Edit</a>
                        </div>
                        <div class="margin-l-10 pull-left divider-left">
                            <a href="#" data-keyid="{{ $key->id }}" class="delete-key delete-icon link-icon"></a>
                        </div>
                    </li>
                @endforeach
            @endif
        </ul>
    </div>
</div>

resources/views/pages/settings/cropper.blade.php
<div id="cropperModal" class="modal fade delete" data-backdrop="static" data-keyboard="false" role="dialog">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title text-center">Upload Company Logo</h4>
                </div>
                <div class="modal-body text-center">
                    <img src="" id="crop-image" width="100%">
                </div>
                <div class="modal-footer  text-center-important">
                    <button class="btn btn-default" id="saveCrop">Done</button>
                </div>

            </div>

        </div>
    </div>
</div>